version: '3.4'



services:
   hostelmanagement:
    container_name: hostel-api
    image: ${DOCKER_REGISTRY-}hostelmanagement
    build:
      context: .
      dockerfile: Dockerfile
   
    ports:
         - 8002:80
         - 8003:443

